### ISSUE TITLE
[BUILD] Bump minimum required Python version to 3.9?

### ISSUE THREAD

**Issue by baggiponte** [functime-org/functime#112]
Dask, NumPy and SciPy only supports Python `>=3.9`. Does this mean we have to update the minimum Python version? We currently use `>=3.8`.

**Comment by topher-lo** [comment]
This makes sense 👍

**Comment by baggiponte** [comment]
Should I make the PR?

**Comment by topher-lo** [comment]
Let's do it. Also need to update the badges in the readme

**Comment by baggiponte** [comment]
Finally time to get back to this. I am preparing a PR. One more thing: since we remove py3.8, we can rework a bit the type hints - no need to import `List` from `typing`, we can annotate with bare `list`. Can I work on those too? Should I create a separate PR for that?

**Comment by baggiponte** [comment]
@topher-lo I think I shall also open another PR to take care of the type annotations currently in place. As I was writing: "since we remove py3.8, we can rework a bit the type hints - no need to import List from typing, we can annotate with bare list". Do you agree with that?

**Comment by topher-lo** [comment]
This would be a breaking change, so let's bundle this PR with 0.10.

**Comment by baggiponte** [comment]
Why would you say it's a breaking change? It's the internal API. But sure!

**Comment by baggiponte** [comment]
Also I forgot to update the badges in the README 😱 How do I generate it from shields.io?

**Comment by topher-lo** [comment]
Users currently using 3.8 when they run pip upgrade functime, an error will occur

**Comment by baggiponte** [comment]
Will postpone this until Py38 actually becomes unsupported (i.e., once 3.13 comes out). I think it's good to support the same Pyversions as polars does.
