### ISSUE TITLE
Fixing failed rolling tests

### ISSUE THREAD

**Issue by abstractqqq** [functime-org/functime#141]
**Describe the bug**
It is a known problem for a while. I am making this ticket to remind me to look into this issue.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by baggiponte** [comment]
Closing as the PR you linked should have addressed this. Thanks! 😊
