### ISSUE TITLE
[CI/CD] Run performance tests as a separate stage

### ISSUE THREAD

**Issue by baggiponte** [functime-org/functime#143]
Running tests in CI always take a ton of time because we also run pytest-benchmark tests. To have a faster feedback loop, we might split those and run performance tests as a separate step. @ngriffiths13 proposed we use codspeed. What are the options? I would run those before merging every PR to ensure that we monitor for performance regressions too.

**Comment by topher-lo** [comment]
I believe benchmarks are disabled https://github.com/functime-org/functime/blob/main/.github/workflows/test.yml

Tests just take a long time right now with 2-core instances.

**Comment by topher-lo** [comment]
One thing to note about the test workflow trigger. It only triggers when a review is requested.
