### ISSUE TITLE
Quickstart fails because we cannot read git LFS parquet files

### ISSUE THREAD

**Issue by baggiponte** [functime-org/functime#148]
Quickstart tests fail because we store the data under git LFS (e.g. [here](https://github.com/functime-org/functime/actions/runs/7232835459/job/19707440561#step:9:21)).

```python
import polars as pl

y = pl.read_parquet(
    "https://github.com/functime-org/functime/raw/main/data/commodities.parquet"
)
```

**Comment by topher-lo** [comment]
Resolved by lfs uninstall
