### ISSUE TITLE
Docs are broken: feature extraction api

### ISSUE THREAD

**Issue by ion-elgreco** [functime-org/functime#156]
https://docs.functime.ai/ref/feature-extraction.md).ai/ref/feature-extraction.md

![image](https://github.com/functime-org/functime/assets/15728914/737dde07-cd6b-48d7-a6fd-e01735d5d129)

**Comment by topher-lo** [comment]
<img width="839" alt="Screenshot 2023-12-28 091044" src="https://github.com/functime-org/functime/assets/46541035/2e1d4845-5c04-43ce-be15-890d5eedf76d">

Fixed.
