### ISSUE TITLE
Reduce Test Runtime in CICD

### ISSUE THREAD

**Issue by ngriffiths13** [functime-org/functime#170]
**Describe the bug**
CICD is failing and running out of free minutes due to long and unnecessary testing.

**To Reproduce**
Run tests in CICD

**Expected behavior**
A quick and sufficient completion of test cases.

**Comment by topher-lo** [comment]
Partially dealt with by: https://github.com/functime-org/functime/pull/175

**Comment by baggiponte** [comment]
Ciao! Now all tests pass (we skip the benchmarking ones). I still would like to shrink CI duration with #212, but that's another topic of discussion. Closing this. And thanks for taking care of it!
