### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by FBruzzesi** [functime-org/functime#173]
There is a tiny list of broken links in the repo which I wouldn't know how to fix:

- [`docs/forecasting.md` ln82](https://github.com/functime-org/functime/blob/main/docs/forecasting.md?plain=1#L82) -> https://composingprograms.com/pages/16-higher-order-functions.html#currying
- [`functime/llm/common` ln 122](https://github.com/functime-org/functime/blob/de448b7b8dabb370f189245c0cd3c429392f5792/functime/llm/common.py#L122) -> https://github.com/openai/openai-python/blob/main/chatml.md

If you know how to replace them, it could be good to do so in #172

**Comment by baggiponte** [comment]
Do you know of a pre commit tool or anything to check spelling (I guess code spell) and broken links? We could add that to the code base.

**Comment by FBruzzesi** [comment]
I tend to use a couple of tools, which, however, I let to be non-blocking in both pre-commit and GHA due to false positives that may be flagged.

- Rust [typos](https://github.com/crate-ci/typos) for checking typos - [example in GHA](https://github.com/FBruzzesi/iso-week-date/blob/main/.github/workflows/check-typos.yaml)
- Rust [mlc](https://github.com/becheran/mlc) and python [deadlink](https://github.com/nschloe/deadlink) for checking links. The former has a GHA ([example](https://github.com/FBruzzesi/iso-week-date/blob/main/.github/workflows/broken-links.yaml)), while the latter I just tend to run on my local.

**Comment by baggiponte** [comment]
Interesting. So you run them on PRs but they are non-blocking?

**Comment by baggiponte** [comment]
Finally closed this. Thanks for reporting, Fra! I'll continue the checks/typos discussion in #202.
