### ISSUE TITLE
Preprocessing roll fill_strategy NameError

### ISSUE THREAD

**Issue by miroslaavi** [functime-org/functime#182]
**Describe the bug**
A tiny bug/typo in the preprocessing roll method for the fill strategy leading to NameError when using roll function. The reason is that the variable name used is X_X_rolling instead of X_rolling in the row 324.

**To Reproduce**
```
import polars as pl
from functime.preprocessing import roll
from pathlib import Path


file_path = Path(__file__).parent.parent / "data" / "commodities.parquet"

df = pl.read_parquet(source=file_path)

transformer = roll(
    window_sizes=[10, 30, 60],
    stats=["sum", "mean", "std"],
    freq="1mo",
    fill_strategy="backward",
)

df.pipe(transformer).collect()
```

**Comment by jrodenbergrheem** [comment]
@baggiponte @miroslaavi Has a fix been rolled out for this?? I am experiencing this exact issue using functime 0.9.5....
