### ISSUE TITLE
`cwt_coefficients` throws `ValueError` when computing `np.convolve`

### ISSUE THREAD

**Issue by khrapovs** [functime-org/functime#206]
**Describe the bug**

```
import polars as pl
from functime.feature_extractors import cwt_coefficients

cwt_coefficients(pl.Series([1 for _ in range(100)]))
```
results in
```
convolution[i] = np.convolve(x.to_numpy(zero_copy_only=True), wavelet_x)
~~~~~~~~~~~^^^
ValueError: could not broadcast input array from shape (119,) into shape (100,)
```

**Expected behavior**

The above code snippet should return a list of floats as promised by the function's signature.

**Desktop (please complete the following information):**

 - OS: MacOS 14.4.1
- `functime`: 0.9.5

**Additional context**

`mode="same"` cures this error, but with this modification later on another error pops up:
```
coeffs.extend(convolution[widths.index(), coeff_idx] for _ in widths)
                              ^^^^^^^^^^^^^^
TypeError: index expected at least 1 argument, got 0
```

**Comment by baggiponte** [comment]
Ciao @khrapovs, thanks for spotting this issue. I did not write the feature engineering code - @abstractqqq and @MathieuCayssol did. Maybe they can provide some support. Otherwise I'll have to make you wait a bit.

**Comment by khrapovs** [comment]
@baggiponte Why wait if I can fix it myself? 😆

**Comment by abstractqqq** [comment]
I saw this and didn't reply immediately because I was doing some improvements on the convolve function in polars_ds. 

I wonder if it is time to let functime depend on polars_ds. Because it can run convolution in Rust and so the expression can be executed in parallel.

**Comment by khrapovs** [comment]
@abstractqqq If you can integrate this into `FeatureExtractor`, would be fantastic. My expertise runs out on Python :(

**Comment by abstractqqq** [comment]
> @abstractqqq If you can integrate this into `FeatureExtractor`, would be fantastic. My expertise runs out on Python :(

Obviously there are some more difficulties/technical details that I need to work through on polars_ds side, and talk to the other maintainers at functime..
