### ISSUE TITLE
Cannot install project dependencies

### ISSUE THREAD

**Issue by montanarograziano** [functime-org/functime#241]
**Describe the bug**
I was trying to setup the project following the [Contributing](https://docs.functime.ai/developer-guide/contributing/) section in doc, but found errors during dependency install.

**To Reproduce**
1. Clone the repo
2. Run `rye sync --features=dev`

**Expected behavior**
Dependencies installed without issues.

**Screenshots**
<img width="1059" alt="image" src="https://github.com/functime-org/functime/assets/40232320/5cd21364-7657-4df2-9f97-e4bff3366604">

**Desktop (please complete the following information):**
 - OS: MacOs
 - Python Version: Tried 3.8, 3.9 and 3.12
**Additional context**
Removing _rust-toolchain.toml_ makes the issue disappear, but causes errors during unit tests.

**Comment by baggiponte** [comment]
Ciao Graziano, thanks for opening the issue.

@abstractqqq do you think it'd be safe to move the rust-toolchain to nightly? v1.79 should be out in two days. We'd need to update the tests again.

@montanarograziano can you show what test fail? If you remove the rust-toolchain is removed, rustup should just use stable rust (1.78) which is older than the version that TQ used to write the code.

**Comment by montanarograziano** [comment]
Oddly enough, I cannot reproduce the errors on the test anymore 😅 I think it was something you fixed in the last commits. Tried different python versions and all tests pass.

**Comment by abstractqqq** [comment]
Last time we updated rust compiler  and package versions. So this should be solved.

**Comment by baggiponte** [comment]
> Last time we updated rust compiler and package versions. So this should be solved.

I don't think that's the case: they are trying straight from master.

---

Rust 1.79 is out today! You can give this another shot, I guess (?):

1. Remove .rust-toolchain.toml
2. `rustup update stable`
3. Run install command

**Comment by abstractqqq** [comment]
The toolchain file will switch to nightly rust I think

**Comment by baggiponte** [comment]
> The toolchain file will switch to nightly rust I think

I think this might be it! I could not compile on stable release so I pushed a commit switching to nightly. Could someone try to see if it builds? Next week I will try to find the time to split functime-rs from python.

**Comment by montanarograziano** [comment]
> > The toolchain file will switch to nightly rust I think
> 
> I think this might be it! I could not compile on stable release so I pushed a commit switching to nightly. Could someone try to see if it builds? Next week I will try to find the time to split functime-rs from python.

Just tested on 3.12 and I confirm I can build and test correctly. Thank you!
